In [46]:
import os
import pandas as pd
from datetime import timedelta

data = pd.read_csv("../../data/supermarket_sales - Sheet1.csv")
print(data)

data = data[["Branch", "Product line", "Date", "Quantity"]]
data["Date"] = pd.to_datetime(data["Date"])
print(data)

min_date = data["Date"].min()
max_date = data["Date"].max()
delta = max_date - min_date

for i in range(delta.days + 1):
    day = min_date + timedelta(days=i)
    for branch in pd.unique(data["Branch"]):
        for product_line in pd.unique(data["Product line"]):
            data.loc[len(data)] = [branch, product_line, day, 0]
data = data.groupby(["Branch", "Product line", "Date"])["Quantity"].sum().reset_index()
print(data)
data.to_pickle("model_data.pkl")

      Invoice ID Branch       City Customer type  Gender  \
0    750-67-8428      A     Yangon        Member  Female   
1    226-31-3081      C  Naypyitaw        Normal  Female   
2    631-41-3108      A     Yangon        Normal    Male   
3    123-19-1176      A     Yangon        Member    Male   
4    373-73-7910      A     Yangon        Normal    Male   
..           ...    ...        ...           ...     ...   
995  233-67-5758      C  Naypyitaw        Normal    Male   
996  303-96-2227      B   Mandalay        Normal  Female   
997  727-02-1313      A     Yangon        Member    Male   
998  347-56-2442      A     Yangon        Normal    Male   
999  849-09-3807      A     Yangon        Member  Female   

               Product line  Unit price  Quantity   Tax 5%      Total  \
0         Health and beauty       74.69         7  26.1415   548.9715   
1    Electronic accessories       15.28         5   3.8200    80.2200   
2        Home and lifestyle       46.33         7  16.2155  

In [21]:
import os
import pandas as pd

data = pd.read_pickle("./model_data.pkl")
print(data)

train_data = pd.DataFrame(columns=["Branch", "Product line", "Month"] + [f"{i}" for i in range(14)] + ["Class"])
branches = pd.unique(data["Branch"])
product_lines = pd.unique(data["Product line"])
j=0

for [branch, product_line], cur_frame in data.groupby(["Branch", "Product line"]):
    values = cur_frame["Quantity"]
    cur_slide = values.iloc[:14].to_list()
    for i in range(14, values.shape[0]):
        label = 1

        if cur_slide[-1] - values.iloc[i] >= cur_slide[-1] * 0.33:
            label = 0
        elif cur_slide[-1] - values.iloc[i] <= cur_slide[-1] * -0.33:
            label = 2
        train_data.loc[len(train_data.index)] = [branch, product_line, cur_frame.iloc[i]["Date"].month] + cur_slide + [label]

        cur_slide.pop(0)
        cur_slide.append(values.iloc[i])
            
train_data = pd.concat([train_data, pd.get_dummies(train_data["Branch"])], axis=1)
train_data = pd.concat([train_data, pd.get_dummies(train_data["Product line"])], axis=1)

train_data.pop("Branch")
train_data.pop("Product line")
train_data = train_data[[c for c in train_data if c not in [f"{i}" for i in range(14)]] 
       + [f"{i}" for i in range(14)]]
            
#print(train_data)
train_data_columns = train_data.iloc[:0].copy().drop(columns=["Class"])
#print(train_data_columns)
train_data_columns.to_pickle("transformed_model_columns.pkl")
train_data.to_pickle("transformed_model_data.pkl")

     Branch            Product line       Date  Quantity
0         A  Electronic accessories 2019-01-01        10
1         A  Electronic accessories 2019-01-02         0
2         A  Electronic accessories 2019-01-03         0
3         A  Electronic accessories 2019-01-04         0
4         A  Electronic accessories 2019-01-05         7
...     ...                     ...        ...       ...
1597      C       Sports and travel 2019-03-26         0
1598      C       Sports and travel 2019-03-27         0
1599      C       Sports and travel 2019-03-28         0
1600      C       Sports and travel 2019-03-29         0
1601      C       Sports and travel 2019-03-30         0

[1602 rows x 4 columns]


In [35]:
import os
import pandas as pd

data = pd.read_pickle("./transformed_model_data.pkl")
#print(data)
train_data = data.sample(frac=0.85)
valid_data = data.drop(train_data.index)
test_data = valid_data.sample(frac=0.5)
valid_data = valid_data.drop(test_data.index)

train_0 = train_data[train_data["Class"] == 0]
train_1 = train_data[train_data["Class"] == 1]
train_2 = train_data[train_data["Class"] == 2]
max_train = (train_0 if train_0.shape[0] >= train_1.shape[0] and train_0.shape[0] >= train_2.shape[0] else
             train_1 if train_1.shape[0] >= train_0.shape[0] and train_1.shape[0] >= train_2.shape[0] else
             train_2)

valid_0 = valid_data[valid_data["Class"] == 0]
valid_1 = valid_data[valid_data["Class"] == 1]
valid_2 = valid_data[valid_data["Class"] == 2]
max_valid = (valid_0 if valid_0.shape[0] >= valid_1.shape[0] and valid_0.shape[0] >= valid_2.shape[0] else
             valid_1 if valid_1.shape[0] >= valid_0.shape[0] and valid_1.shape[0] >= valid_2.shape[0] else
             valid_2)

for data_item in [train_0, train_1, train_2]:
    cur_num = data_item.shape[0]
    while cur_num + data_item.shape[0] < max_train.shape[0]:
        train_data = pd.concat([train_data, data_item])
        cur_num += data_item.shape[0]

for data_item in [valid_0, valid_1, valid_2]:
    cur_num = data_item.shape[0]
    while cur_num + data_item.shape[0] < max_valid.shape[0]:
        valid_data = pd.concat([valid_data, data_item])
        cur_num += data_item.shape[0]
        
print((data["Class"] == 0).sum() / data.shape[0])
print((data["Class"] == 1).sum() / data.shape[0])
print((data["Class"] == 2).sum() / data.shape[0])
print()

print((train_data["Class"] == 0).sum() / train_data.shape[0])
print((train_data["Class"] == 1).sum() / train_data.shape[0])
print((train_data["Class"] == 2).sum() / train_data.shape[0])
print()

print((valid_data["Class"] == 0).sum() / valid_data.shape[0])
print((valid_data["Class"] == 1).sum() / valid_data.shape[0])
print((valid_data["Class"] == 2).sum() / valid_data.shape[0])
print()

print(pd.merge(train_data, valid_data).shape[0])
print()

train_data.to_pickle("train_data.pkl")
valid_data.to_pickle("valid_data.pkl")
test_data.to_pickle("test_data.pkl")

0.6
0.05185185185185185
0.34814814814814815

0.39187643020594964
0.37757437070938216
0.2305491990846682

0.3959731543624161
0.3624161073825503
0.24161073825503357

0



In [51]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

np.random.seed(42)
tf.random.set_seed(seed=42)

BATCH_SIZE = 256

train_data_pd = pd.read_pickle("./train_data.pkl")
valid_data_pd = pd.read_pickle("./valid_data.pkl")
train_class_pd = train_data_pd.pop("Class")
valid_class_pd = valid_data_pd.pop("Class")

input_data = tf.convert_to_tensor(train_data_pd.values.reshape(-1, 1, train_data_pd.shape[1]))
input_labels = tf.convert_to_tensor(train_class_pd.values.reshape(-1, 1, 1), dtype=tf.float32)
valid_data = tf.convert_to_tensor(valid_data_pd.values.reshape(-1, 1, valid_data_pd.shape[1]))
valid_labels = tf.convert_to_tensor(valid_class_pd.values.reshape(-1, 1, 1), dtype=tf.float32)

model = keras.models.Sequential([
    layers.LSTM(units=30, input_shape=(1, train_data_pd.shape[1]), return_sequences=True),
    layers.Dense(units=1),
    layers.Reshape([1,-1])
])
loss = keras.losses.MeanSquaredError()
optimizer = keras.optimizers.RMSprop(learning_rate=0.0025)
metrics = [keras.metrics.CategoricalCrossentropy(), keras.metrics.MeanSquaredError()]
model.compile(
    optimizer=optimizer,
    loss=loss,
    metrics=metrics
)
model.fit(x=input_data, y=input_labels, epochs=40, batch_size=BATCH_SIZE)
print("Training Accuracy: ", float(tf.divide(tf.reduce_sum(tf.cast(tf.equal(tf.round(model(input_data)), input_labels), tf.int32)), tf.shape(input_labels)[0])))
print("Valid Accuracy: ", float(tf.divide(tf.reduce_sum(tf.cast(tf.equal(tf.round(model(valid_data)), valid_labels), tf.int32)), tf.shape(valid_labels)[0])))

model.save("./model.h5")

Epoch 1/40
7/7 [==============================] - 2s 6ms/step - loss: 0.9581 - categorical_crossentropy: 9.9978e-08 - mean_squared_error: 0.9581
Epoch 2/40
7/7 [==============================] - 0s 7ms/step - loss: 0.6657 - categorical_crossentropy: 9.9978e-08 - mean_squared_error: 0.6657
Epoch 3/40
7/7 [==============================] - 0s 7ms/step - loss: 0.6074 - categorical_crossentropy: 9.9978e-08 - mean_squared_error: 0.6074
Epoch 4/40
7/7 [==============================] - 0s 7ms/step - loss: 0.5792 - categorical_crossentropy: 9.9978e-08 - mean_squared_error: 0.5792
Epoch 5/40
7/7 [==============================] - 0s 7ms/step - loss: 0.5551 - categorical_crossentropy: 9.9978e-08 - mean_squared_error: 0.5551
Epoch 6/40
7/7 [==============================] - 0s 7ms/step - loss: 0.5363 - categorical_crossentropy: 9.9978e-08 - mean_squared_error: 0.5363
Epoch 7/40
7/7 [==============================] - 0s 7ms/step - loss: 0.5202 - categorical_crossentropy: 9.9978e-08 - mean_squared

In [50]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

np.random.seed(42)
tf.random.set_seed(seed=42)

BATCH_SIZE = 256

train_data_pd = pd.read_pickle("./train_data.pkl")
valid_data_pd = pd.read_pickle("./valid_data.pkl")
train_class_pd = train_data_pd.pop("Class")
valid_class_pd = valid_data_pd.pop("Class")

input_data = tf.convert_to_tensor(train_data_pd.values.reshape(-1, 1, train_data_pd.shape[1]))
input_labels = tf.convert_to_tensor(train_class_pd.values.reshape(-1, 1, 1), dtype=tf.float32)
valid_data = tf.convert_to_tensor(valid_data_pd.values.reshape(-1, 1, valid_data_pd.shape[1]))
valid_labels = tf.convert_to_tensor(valid_class_pd.values.reshape(-1, 1, 1), dtype=tf.float32)

model = keras.models.load_model("./model.h5")
model.fit(x=input_data, y=input_labels, epochs=10, batch_size=BATCH_SIZE)

print("Training Accuracy: ", float(tf.divide(tf.reduce_sum(tf.cast(tf.equal(tf.round(model(input_data)), input_labels), tf.int32)), tf.shape(input_labels)[0])))
print("Valid Accuracy: ", float(tf.divide(tf.reduce_sum(tf.cast(tf.equal(tf.round(model(valid_data)), valid_labels), tf.int32)), tf.shape(valid_labels)[0])))

model.save("./model.h5")

Epoch 1/10
7/7 [==============================] - 2s 4ms/step - loss: 0.0780 - categorical_crossentropy: 9.9978e-08 - mean_squared_error: 0.0780
Epoch 2/10
7/7 [==============================] - 0s 5ms/step - loss: 0.0783 - categorical_crossentropy: 9.9978e-08 - mean_squared_error: 0.0783
Epoch 3/10
7/7 [==============================] - 0s 4ms/step - loss: 0.0619 - categorical_crossentropy: 9.9978e-08 - mean_squared_error: 0.0619
Epoch 4/10
7/7 [==============================] - 0s 5ms/step - loss: 0.0878 - categorical_crossentropy: 9.9978e-08 - mean_squared_error: 0.0878
Epoch 5/10
7/7 [==============================] - 0s 5ms/step - loss: 0.0584 - categorical_crossentropy: 9.9978e-08 - mean_squared_error: 0.0584
Epoch 6/10
7/7 [==============================] - 0s 5ms/step - loss: 0.0713 - categorical_crossentropy: 9.9978e-08 - mean_squared_error: 0.0713
Epoch 7/10
7/7 [==============================] - 0s 5ms/step - loss: 0.0709 - categorical_crossentropy: 9.9978e-08 - mean_squared

In [52]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

test_data_pd = pd.read_pickle("./test_data.pkl")
test_class_pd = test_data_pd.pop("Class")

test_data = tf.convert_to_tensor(test_data_pd.values.reshape(-1, 1, test_data_pd.shape[1]))
test_labels = tf.convert_to_tensor(test_class_pd.values.reshape(-1, 1, 1), dtype=tf.float32)

model = keras.models.load_model("./model.h5")

predictions = tf.round(model(test_data))

equals_0 = float(tf.reduce_sum(tf.cast(tf.logical_and(tf.equal(predictions, test_labels), tf.equal(test_labels, 0)), tf.int32)))
missed_0 = float(tf.reduce_sum(tf.cast(tf.logical_and(tf.equal(test_labels, 0), tf.not_equal(predictions, 0)), tf.int32)))
guessed_0 = float(tf.reduce_sum(tf.cast(tf.logical_and(tf.not_equal(test_labels, 0), tf.equal(predictions, 0)), tf.int32)))

equals_1 = float(tf.reduce_sum(tf.cast(tf.logical_and(tf.equal(predictions, test_labels), tf.equal(test_labels, 1)), tf.int32)))
missed_1 = float(tf.reduce_sum(tf.cast(tf.logical_and(tf.equal(test_labels, 1), tf.not_equal(predictions, 1)), tf.int32)))
guessed_1 = float(tf.reduce_sum(tf.cast(tf.logical_and(tf.not_equal(test_labels, 1), tf.equal(predictions, 1)), tf.int32)))

equals_2 = float(tf.reduce_sum(tf.cast(tf.logical_and(tf.equal(predictions, test_labels), tf.equal(test_labels, 2)), tf.int32)))
missed_2 = float(tf.reduce_sum(tf.cast(tf.logical_and(tf.equal(test_labels, 2), tf.not_equal(predictions, 2)), tf.int32)))
guessed_2 = float(tf.reduce_sum(tf.cast(tf.logical_and(tf.not_equal(test_labels, 2), tf.equal(predictions, 2)), tf.int32)))

print("Precision 0:", equals_0 / (equals_0 + guessed_0))
print("Recall 0:", equals_0 / (equals_0 + missed_0))
print("Precision 1:", equals_1 / (equals_1 + guessed_1))
print("Recall 1:", equals_1 / (equals_1 + missed_1))
print("Precision 2:", equals_2 / (equals_2 + guessed_2))
print("Recall 2:", equals_2 / (equals_2 + missed_2))
print("Accuracy: ", float(tf.divide(tf.reduce_sum(tf.cast(tf.equal(predictions, test_labels), tf.int32)), tf.shape(test_labels)[0])))

Precision 0: 0.7586206896551724
Recall 0: 0.3333333333333333
Precision 1: 0.01694915254237288
Recall 1: 0.25
Precision 2: 0.5
Recall 2: 0.16129032258064516
Accuracy:  0.27722772277227725


In [56]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from collections import OrderedDict

np.random.seed(42)
tf.random.set_seed(seed=42)

BATCH_SIZE = 256

train_ds = tf.data.experimental.make_csv_dataset(
    "train_data.csv",
    batch_size=BATCH_SIZE,
    num_epochs=1,
    ignore_errors=True,
    label_name="Class"
)

valid_ds = tf.data.experimental.make_csv_dataset(
    "valid_data.csv",
    batch_size=BATCH_SIZE,
    num_epochs=1,
    ignore_errors=True,
    label_name="Class"
)

def map_func(x, class_):
    od_ = OrderedDict()
    od_["lstm_input"] = tf.reshape(tf.stack(list(x.values())), (-1, 1, len(list(x.values()))))
    class_ = tf.reshape(class_, (-1, 1, 1))
    return (od_, class_)

train_ds = train_ds.map(map_func)
valid_ds = valid_ds.map(map_func)

model = keras.models.Sequential([
    layers.LSTM(units=30, input_shape=(1, 24), return_sequences=True, name="lstm"),
    layers.Dense(units=1),
    layers.Reshape([1,-1])
])
loss = keras.losses.MeanSquaredError()
optimizer = keras.optimizers.RMSprop(learning_rate=0.0005)
metrics = [keras.metrics.CategoricalCrossentropy(), keras.metrics.MeanSquaredError()]
model.compile(
    optimizer=optimizer,
    loss=loss,
    metrics=metrics
)
model.fit(x=train_ds, epochs=25, batch_size=BATCH_SIZE)


num_accur_train = 0
total_train = 0
for batch in train_ds:
    res = model(batch[0]["lstm_input"])
    num_accur_train += int(tf.reduce_sum(tf.cast(tf.equal(tf.cast(tf.round(res), tf.int32), batch[1]), tf.int32)))
    total_train += int(tf.shape(batch[1])[0])

num_accur_valid = 0
total_valid = 0
for batch in valid_ds:
    res = model(batch[0]["lstm_input"])
    num_accur_valid += int(tf.reduce_sum(tf.cast(tf.equal(tf.cast(tf.round(res), tf.int32), batch[1]), tf.int32)))
    total_valid += int(tf.shape(batch[1])[0])

print("Training Accuracy: ", num_accur_train / total_train)
print("Valid Accuracy: ", num_accur_valid / total_valid)

model.save("./model.h5")

Epoch 1/25
7/7 [==============================] - 2s 5ms/step - loss: 1.0530 - categorical_crossentropy: 9.8604e-08 - mean_squared_error: 1.0530
Epoch 2/25
7/7 [==============================] - 0s 3ms/step - loss: 0.8974 - categorical_crossentropy: 9.8604e-08 - mean_squared_error: 0.8974
Epoch 3/25
7/7 [==============================] - 0s 4ms/step - loss: 0.8701 - categorical_crossentropy: 9.8604e-08 - mean_squared_error: 0.8701
Epoch 4/25
7/7 [==============================] - 0s 3ms/step - loss: 0.8188 - categorical_crossentropy: 9.8604e-08 - mean_squared_error: 0.8188
Epoch 5/25
7/7 [==============================] - 0s 3ms/step - loss: 0.8155 - categorical_crossentropy: 9.8604e-08 - mean_squared_error: 0.8155
Epoch 6/25
7/7 [==============================] - 0s 3ms/step - loss: 0.7942 - categorical_crossentropy: 9.8604e-08 - mean_squared_error: 0.7942
Epoch 7/25
7/7 [==============================] - 0s 3ms/step - loss: 0.7879 - categorical_crossentropy: 9.8604e-08 - mean_squared

In [68]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from collections import OrderedDict

model = keras.models.load_model("./model.h5")
weights = model.get_weights()
for weight in weights:
    #print(weight)
    print(tf.shape(weight))

tf.Tensor([ 24 120], shape=(2,), dtype=int32)
tf.Tensor([ 30 120], shape=(2,), dtype=int32)
tf.Tensor([120], shape=(1,), dtype=int32)
tf.Tensor([30  1], shape=(2,), dtype=int32)
tf.Tensor([1], shape=(1,), dtype=int32)
